#!/usr/bin/env bash

set -e

package_name="$1"
package_version="$2"
dist_tag="$3"
circle_build_num="$4"
circle_branch="$5"

if [[ $circle_branch == "master" ]]; then
    # Publish to Verdaccio
    yarn publish --tag latest --new-version $package_version

    # Overwrite .npmrc to point to Gemfury
    rm .npmrc
    echo '@themuse:registry=https://npm.fury.io/themuse/' >> .npmrc
    url='//npm.fury.io/themuse/:_authToken=${GEMFURY_PUSH_TOKEN}'
    echo $url >> .npmrc

    # Publish to Gemfury
    yarn publish --tag latest --new-version $package_version
else
    yarn --no-git-tag-version --new-version version "$package_version-build-$circle_build_num"
    
    # Publish to Verdaccio
    yarn publish --tag $dist_tag

    # Overwrite .npmrc to point to Gemfury
    rm .npmrc
    echo '@themuse:registry=https://npm.fury.io/themuse/' >> .npmrc
    url='//npm.fury.io/themuse/:_authToken=${GEMFURY_PUSH_TOKEN}'
    echo $url >> .npmrc

    # Publish to Gemfury
    yarn publish --tag $dist_tag

    echo "To install via dist-tag: yarn install --save $package_name@$dist_tag"
fi